### ISSUE TITLE
style html

### ISSUE THREAD

**Issue by russtelen** [russtelen/FOOD-ORDERING-APP#1]

**Comment by Hirak-Pandya** [comment]
Can I work on this issue?

**Comment by hambali999** [comment]
hi can u label it hacktoberfest-accepted and the topic to be hacktoberfest? 

I am willing to contribute in this repo

**Comment by hambali999** [comment]
Will make more changes in the future to enhance the application, and also will add more information in the future in the README.md file :) 👍
Hi i have created a PR pls merge it to view the new styling of the html etc #4
